languageCode = "zh-cn"
languageName = "Simplified Chinese"
weight = 1
title = "丁子元的博客"


[params]
  displayName = "ZH-CN"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/ding.png"
  description = "丁子元的博客"

[author]
name = "丁子元"
image = "img/ding.png"
bio = "曾经做过业务开发、CICD。对homelab有兴趣。"
links = [
  { github = "https://github.com/ziyuanding" }
]
