# config/_default/params.toml

colorScheme = "blowfish"

defaultBackgroundImage = "img/background.svg"

[article]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true