# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
        sudo dpkg -i pandoc-3.1.9-1-amd64.deb
        rm pandoc-3.1.9-1-amd64.deb

    - name: Convert typ to HTML
      run: |
        ls -l -a
        pwd
        .github/workflows/workflow.sh

    - name: Commit and push changes
      run: |
        git config --local user.email ${{ secrets.MY_GITHUB_EMAIL }}
        git config --local user.name ${{ secrets.MY_GITHUB_USERNAME }}
        git add -A .
        git commit -m "Convert typ to HTML"
        git push
